config/routes.rb
Rails.application.routes.draw do
  root to: "blogs#index"
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
    @blog = Blog.new
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    Blog.create(blog_params)
    redirect_to blogs_path
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path
      flash[:notice] = "You have updated book successfully."
    else
      render:edit
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :start_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<div class='container px-5 px-0'>
  <div class="row">
    <div class="col-md-6">
      <%= form_with model: @blog, url: blog_path, method: :patch do |f| %>
       <div class="title">
         <div class="form_tag">タイトル</div>
         <%= f.text_field :title %>
       </div>
       <div class="content">
         <div class="form_tag">内容</div>
         <%= f.text_field :content %>
       </div>
       <div class="time">
         <div class="form_tag">時間</div>
         <%= f.datetime_select :start_time %>
       </div>
       <div class="pt-2">
          <%= f.submit "登録する", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class='container px-0'>
  <p id="notice"><%= notice %></p>
    <div>
      <h1>カレンダー</h1>
      <div class="row">
        <div class="col-md-4">
          <div class="schedule">今後の予定一覧</div>
          <table class="table">
            <thead>
              <tr>
                <th>タイトル</th>
                <th>日程</th>
              </tr>
            </thead>
            <tbody>
              <% @blogs.each do |blog| %>
               <tr>
                 <td><%= link_to blog.title,blog %></td>
                 <td><%= blog.created_at.strftime("%m-%d") %></td>
               </tr>
              <% end %>
            </tbody>
          </table>
          <%= form_with model: @blog, url: blogs_path, method: :post do |f| %>
           <div class="title">
             <div class="form_tag">タイトル</div>
             <%= f.text_field :title %>
           </div>
           <div class="content">
             <div class="form_tag">内容</div>
             <%= f.text_field :content %>
           </div>
           <div class="time">
             <div class="form_tag">時間</div>
             <%= f.datetime_select :start_time %>
           </div>
           <div class="pt-2">
              <%= f.submit "登録する", class: 'btn btn-success' %>
            </div>
          <% end %>
        </div>
      <br>
      <div class="col-md-8">
         <%= month_calendar events: @blogs do |date, blogs| %>
           <%= date.day %>
             <% blogs.each do |blog| %>
               <%= link_to blog.title, blog %>
             <% end %>
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class='container px-5 px-0'>
 <p id="notice"><%= notice %></p>
 <div class="row">
  <div class="col-md-6 offset-2">
    <div class="show">
     <div>タイトル</div>
      <%= @blog.title %>
     <div>内容</div>
      <%= @blog.content %>
     <div>日時</div>
      <%= @blog.start_time.strftime("%m-%d") %>
     <%= link_to "編集", edit_blog_path(@blog) %>
     <%= link_to "削除" , blog_path(@blog.id), method: :delete, data:{ confirm: "本当に消していいですか？" } %>
     <%= link_to "戻る", blogs_path %>
    </div>
  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calender</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>